### ISSUE TITLE
garbage. amend or delete repo

### ISSUE THREAD

**Issue by eddyojb88** [chrisk314/django-celery-docker-example#5]
thanks for wasting 45 minutes of my time.

**Comment by chrisk314** [comment]
You're a cretin. People in general must hate you if this is a reflection of your behaviour. I pity you.

At the time you opened this issue the repo hadn't been updated in three years... Use your brain in future and learn how to check the last updated date.

When you open an issue on a repo, provide a description of what the problem is instead of just acting like a brattish, entitled, asshole.

Thanks for wasting 45 seconds of my time. Amend or delete yourself.
